# Competencias reflejadas en el proyecto 
## Primera entrega

| Tipo de competencia 	| Competencia                                                                                                                                                                                                                                             	| Aprendizaje y justificación                                                                                                                                                                                                                                                     	| Actividades donde se desarrolló 	|   	|
|---------------------	|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|---------------------------------	|---	|
| Genérica            	| Se comunica en español en forma oral y escrita en sus intervenciones profesionales y en su vida personal, utilizando correctamente el idioma.                                                                                                           	| Nos comunicamos todos los días en clases de la asignatura y en reuniones de duda o retroalimentación y en reuniones de equipo.                                                                                                                                                  	| Todas las actividades           	|   	|
| Genérica            	| Usa las TIC en sus intervenciones profesionales y en su vida personal de manera pertinente y responsable                                                                                                                                                	| Todas las actividades y las tareas encomendadas relacionadas a la realización del proyecto las realizamos de manera digital, la misma planeación de las actividades está hecha por medio de una plataforma para gestionar la información.                                       	| Todas las actividades           	|   	|
| Disciplinar         	| Analiza la evolución disciplinar de la Ingeniería de Software, así como las características del profesionista vinculado con la misma, de acuerdo con el marco teórico y los modelos curriculares de la disciplina.                                      	| Al principio de la asignatura se nos dio a conocer los inicios de la ingeniería del software, la manera en como se construía en software en esos años, la manera en la que fue cambiando, la razón por la que este cambio fue necesario y las bases que ahora tiene.            	|                                 	|   	|
| Disciplinar         	| Analiza los principales métodos, técnicas, procedimientos y buenas prácticas utilizados en las fases de requisitos, diseño, codificación, pruebas y mantenimiento del software, de acuerdo con el cuerpo de conocimientos reconocido por la disciplina. 	| En las clases de la asignatura hemos platicado sobre las diferentes fases del desarrollo del software, así como la importancia de cada una, las maneras de realizarlas, los diferentes ciclos de manejo que estas fases podrían tener y los conceptos más importantes de estas. 	|                                 	|   	|
|                     	|                                                                                                                                                                                                                                                         	|                                                                                                                                                                                                                                                                                 	|                                 	|   	|
